[package]
name = "flint-architectures"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
flint-backend.workspace = true
flint-checkpoint.workspace = true
flint-error.workspace = true
flint-model.workspace = true
flint-tensor.workspace = true
flint-tokenizer.workspace = true
serde_json.workspace = true
