[package]
name = "flint-model"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
flint-backend.workspace = true
flint-checkpoint.workspace = true
flint-error.workspace = true
flint-num.workspace = true
flint-tensor.workspace = true
serde_json.workspace = true
