[package]
name = "flint-backend"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bytemuck.workspace = true
flint-error.workspace = true
flint-gpu.workspace = true
flint-kernel.workspace = true
flint-profiler.workspace = true
flint-tensor.workspace = true

[dev-dependencies]
flint-num.workspace = true
