[package]
name = "flint-server"
version.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
flint-architectures.workspace = true
flint-backend.workspace = true
flint-error.workspace = true
flint-generate.workspace = true
flint-fetch.workspace = true
flint-tokenizer.workspace = true
axum.workspace = true
clap.workspace = true
env_logger.workspace = true
futures-core.workspace = true
futures-util.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tower-http.workspace = true
