[package]
name = "saturn-mtl"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
saturn-core.workspace = true
saturn-compiler.workspace = true
saturn-shader.workspace = true
log.workspace = true

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
objc2 = "0.6"
objc2-foundation = { version = "0.3", features = ["std", "NSError", "NSString"] }
objc2-metal = { version = "0.3", default-features = false, features = [
    "std",
    "MTLAllocation",
    "MTLBlitCommandEncoder",
    "MTLBuffer",
    "MTLCommandBuffer",
    "MTLCommandEncoder",
    "MTLCommandQueue",
    "MTLComputeCommandEncoder",
    "MTLComputePipeline",
    "MTLDevice",
    "MTLLibrary",
    "MTLResource",
    "MTLTypes",
] }
