[package]
name = "flint-examples"
version.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
flint-architectures.workspace = true
flint-backend.workspace = true
flint-error.workspace = true
flint-generate.workspace = true
flint-fetch.workspace = true
flint-tokenizer.workspace = true
clap.workspace = true
env_logger.workspace = true
serde_json.workspace = true
ureq.workspace = true

[[example]]
name = "chat"
path = "chat/main.rs"

[[example]]
name = "schema"
path = "schema/main.rs"
