@workgroup_size(256, 1, 1)
kernel concat (@binding(0) a: buf<f32>, @binding(1) b: buf<f32>, @binding(2) y: buf<f32>, ROWS: u32, D: u32) {
    if global_id().x < ROWS * 2 * D {
        let row = global_id().x / (2 * D);
        let d = global_id().x % (2 * D);
        if d < D {
            y[global_id().x] = a[row * D + d];
        } else {
            y[global_id().x] = b[row * D + d - D];
        }
    }
}
