@workgroup_size(256, 1, 1)
kernel conv1d (@binding(0) x: buf<f32>, @binding(1) weight: buf<f32>, @binding(2) state: buf<f32>, @binding(3) y: buf<f32>, DIM: u32) {
    if global_id().x < DIM {
        let c = global_id().x;
        let s0 = state[c * 3];
        let s1 = state[c * 3 + 1];
        let s2 = state[c * 3 + 2];
        let xc = x[c];
        let v = weight[c * 4] * s0 + weight[c * 4 + 1] * s1 + weight[c * 4 + 2] * s2 + weight[c * 4 + 3] * xc;
        state[c * 3] = s1;
        state[c * 3 + 1] = s2;
        state[c * 3 + 2] = xc;
        y[c] = v / (1.0 + exp(-v));
    }
}
