@workgroup_size(256, 1, 1)
kernel merge_qkv
    (@binding(0) partial: buf<f32>, @binding(1) yq: buf<f32>, @binding(2) yk: buf<f32>, @binding(3) yv: buf<f32>,
     NQ: u32, NK: u32, NV: u32, SEGS: u32)
{
    let ntot = NQ + NK + NV;
    let col = group_id().x * 256 + local_id().x;
    let mut s = 0.0;
    if col < NQ {
        for i in 0..SEGS {
            s = s + partial[i * ntot + col];
        }
        yq[col] = s;
    } else if col < NQ + NK {
        let c = col - NQ;
        for i in 0..SEGS {
            s = s + partial[i * ntot + NQ + c];
        }
        yk[c] = s;
    } else if col < ntot {
        let c = col - NQ - NK;
        for i in 0..SEGS {
            s = s + partial[i * ntot + NQ + NK + c];
        }
        yv[c] = s;
    }
}
