@workgroup_size(256, 1, 1)
kernel mul (@binding(0) a: buf<f32>, @binding(1) b: buf<f32>, @binding(2) y: buf<f32>, N: u32, M: u32, MODE: u32, STRIDE: u32, OFFSET: u32) {
    if global_id().x < N {
        if MODE == 1 {
            y[global_id().x] = a[global_id().x] * b[(global_id().x / M) * STRIDE + OFFSET + global_id().x % M];
        } else {
            y[global_id().x] = a[global_id().x] * b[global_id().x % M];
        }
    }
}
