@workgroup_size(16, 16, 1)
kernel gemm_cm
    (@binding(0) a: buf<f16>, @binding(1) b: buf<f16>, @binding(2) c: buf<f32>, m: u32, n: u32, k: u32)
{
    const TILE: u32 = 16;
    let mut a_tile: threadgroup<[f16; 16 * 16]>;
    let mut b_tiles: threadgroup<[f16; 16 * 16 * 8]>;
    let sg_count = (256 + subgroup_size() - 1) / subgroup_size();
    let sg = subgroup_id();
    let base_row = group_id().y * TILE;
    let base_col = group_id().x * 128 + sg * TILE;
    let mut acc: matrix<f32> = coop_zero();
    if base_col < n {
        a_tile[local_id().y * 16 + local_id().x] = a[(base_row + local_id().y) * k + local_id().x];
        let lty = local_id().y - sg * 2;
        @unroll for j in 0..8 {
            let by = lty + j * 2;
            b_tiles[sg * 256 + j * 32 + lty * 16 + local_id().x] =
                b[by * n + base_col + local_id().x];
        }
    }
    barrier();
    if base_col < n {
        let am = coop_load_a(a_tile, 16, true);
        let bm = coop_load_b(b_tiles[sg * 256], 16, true);
        acc = coop_mul_add(am, bm, acc);
        coop_store(c[base_row * n + base_col], acc, n, true);
    }
}
