@workgroup_size(16, 16, 1)
kernel gemm
    (@binding(0) a: buf<f16>, @binding(1) b: buf<f16>, @binding(2) c: buf<f32>, m: u32, n: u32, k: u32)
{
    const TILE: u32 = 16;
    let mut a_tile: threadgroup<[f16; 16 * 16]>;
    let mut b_tile: threadgroup<[f16; 16 * 16]>;
    let row = group_id().y * TILE + local_id().y;
    let col = group_id().x * TILE + local_id().x;
    let mut acc: f32 = 0.0;
    for i in 0..((k + 15) / 16) {
        barrier();
        let base = i * 16;
        let ai = (group_id().y * 16 + local_id().y) * k + base + local_id().x;
        a_tile[local_id().y * 16 + local_id().x] = ai < m * k ? a[ai] : 0.0 as f16;
        let bi = (base + local_id().y) * n + group_id().x * 16 + local_id().x;
        b_tile[local_id().y * 16 + local_id().x] = bi < k * n ? b[bi] : 0.0 as f16;
        barrier();
        @unroll for j in 0..16 {
            acc += a_tile[local_id().y * 16 + j] as f32 * b_tile[j * 16 + local_id().x] as f32;
        }
    }
    if row < m && col < n {
        c[row * n + col] = acc;
    }
}
